//
// COMPONENT_FRAME_CLASS.hpp
//
// Created: COMPONENT_FRAME_DATE
//  Author:
//

#if !defined(COMPONENTS_COMPONENT_FRAME_UPPER_CLASS_HPP_)
#define COMPONENTS_COMPONENT_FRAME_UPPER_CLASS_HPP_

namespace COMPONENT_FRAME_NAMESPACE {

class COMPONENT_FRAME_CLASS {
public:
	void initialize();
};

}  // namespace COMPONENT_FRAME_NAMESPACE

#endif  // COMPONENTS_COMPONENT_FRAME_UPPER_CLASS_HPP_
